trigger:
  branches:
    include:
      - main  # Set to your main branch name

pool:
  vmImage: 'ubuntu-latest'  # Specify the VM image to use

variables:
  buildConfiguration: 'Release'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-DskipTests=true'
    displayName: 'Build with Maven'

  - task: CopyFiles@2
    inputs:
      contents: '**/target/*.jar'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy JAR file to staging'

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: drop
    displayName: 'Publish Artifact'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
    displayName: 'Run Tests'